/* 
Project Euler
Problem 2
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding 
the previous two terms. By starting with 1 and 2, the first 10 
terms will be:

		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.

1) Create array of Fibonacci Sequence whose value < 4000000
	fibonacci equation x = (x-1)+(x-2)
	
2) push even numbers to array

3) reduce

*/

/*
//function fibArray(valLessThan) {
//	for (var i = 0; i < valLessThan; i++){
		function fibonacci(nTerms) {
			var fib=[0,1]; //initialize with first 2 terms
			for (j=2; fib.length < nTerms; j++){
				fib[j]=fib[j-2]+fib[j-1]
				
			}
			console.log(fib);
		}
		
		fibonacci();
}

fibArray(10);

*/


function fib(n) {
	var a=0;
	var b=1;
	var f;
	while (f < n) {
		f=a+b;
		b=a;
		a=f;
		console.log(f);
		
		
	}

}

fib(100);
















