/* 
Project Euler
Problem 2
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding 
the previous two terms. By starting with 1 and 2, the first 10 
terms will be:

		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.



while current term of fibonacci sequence < 4000000
	continure generating terms
	
if term is even
	add value to sum variable
	
*/

function evenFibSum(maxNum){
    var fibSum=0;
	var a = 0;
	var b = 1;
	var current;
	
	do {
		current = a + b;
		b = a;
		a = current;
		
		if (current%2==0) {
			fibSum+=current;
			console.log(current)
		}
		
	} while ( current < maxNum);
	console.log( "The sum of even Fibonacci Numbers less than " + maxNum + " is " + fibSum);
};

evenFibSum(1000);